import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set plot style
plt.style.use("ggplot")
sns.set_theme(style="whitegrid")


def load_and_clean_data(filepath="dataset_flats.csv"):
    df = pd.read_csv(filepath)

    # Drop rows without critical information
    df = df.dropna(subset=["Total_Price_EUR", "Area"])

    # Clean 'Rooms' column to extract numeric values (e.g., '5+' becomes 5.0)
    if "Rooms" in df.columns:
        df["Rooms_Numeric"] = (
            df["Rooms"].astype(str).str.extract(r"(\d+\.?\d*)").astype(float)
        )

    # Filter out extreme outliers for better visualization (e.g., top 1% of prices/areas)
    if not df.empty:
        price_cap = df["Total_Price_EUR"].quantile(0.99)
        area_cap = df["Area"].quantile(0.99)
        df = df[(df["Total_Price_EUR"] <= price_cap) & (df["Area"] <= area_cap)]

    return df


def basic_dataset_info(df):
    print("--- DATASET INFO ---")
    print(df.info())
    print("\n--- MISSING VALUES ---")
    print(df.isnull().sum())
    print("\n--- SUMMARY STATISTICS ---")
    print(df.describe())


def plot_distributions(df):
    fig, axes = plt.subplots(1, 2, figsize=(15, 5))

    # Total Price Distribution
    sns.histplot(df["Total_Price_EUR"], bins=50, kde=True, color="blue", ax=axes[0])
    axes[0].set_title("Distribution of Total Price (EUR)")
    axes[0].set_xlabel("Price (EUR)")
    axes[0].set_ylabel("Frequency")

    # Area Distribution
    sns.histplot(df["Area"], bins=50, kde=True, color="green", ax=axes[1])
    axes[1].set_title("Distribution of Area")
    axes[1].set_xlabel(
        f"Area ({df['Area_Unit'].iloc[0] if not df['Area_Unit'].empty else 'm2'})"
    )
    axes[1].set_ylabel("Frequency")

    plt.tight_layout()
    plt.show()


def plot_relationships(df):
    fig, axes = plt.subplots(1, 2, figsize=(15, 5))

    # Price vs Area Scatter Plot
    sns.scatterplot(x="Area", y="Total_Price_EUR", data=df, alpha=0.6, ax=axes[0])
    axes[0].set_title("Price vs. Area")
    axes[0].set_xlabel("Area")
    axes[0].set_ylabel("Total Price (EUR)")

    # Price per Municipality Boxplot
    if "Municipality" in df.columns and not df["Municipality"].isnull().all():
        # Get top 10 most frequent municipalities to keep the plot readable
        top_municipalities = df["Municipality"].value_counts().nlargest(10).index
        df_top_muni = df[df["Municipality"].isin(top_municipalities)]

        sns.boxplot(x="Municipality", y="Total_Price_EUR", data=df_top_muni, ax=axes[1])
        axes[1].set_title("Price Distribution by Top 10 Municipalities")
        axes[1].set_xticklabels(axes[1].get_xticklabels(), rotation=45, ha="right")
        axes[1].set_xlabel("Municipality")
        axes[1].set_ylabel("Total Price (EUR)")
    else:
        axes[1].set_visible(False)

    plt.tight_layout()
    plt.show()


def plot_correlation_matrix(df):
    # Select only numeric columns for correlation
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    corr_matrix = df[numeric_cols].corr()

    plt.figure(figsize=(10, 8))
    sns.heatmap(
        corr_matrix,
        annot=True,
        cmap="coolwarm",
        fmt=".2f",
        vmin=-1,
        vmax=1,
        square=True,
    )
    plt.title("Correlation Heatmap of Numeric Features")
    plt.tight_layout()
    plt.show()


def main_eda():
    # Replace 'dataset_flats.csv' with the actual filename generated by the scraper
    dataset_file = "dataset_flats.csv"

    try:
        df = load_and_clean_data(dataset_file)

        basic_dataset_info(df)
        plot_distributions(df)
        plot_relationships(df)
        plot_correlation_matrix(df)

    except FileNotFoundError:
        print(f"Error: File '{dataset_file}' not found. Please run the scraper first.")


if __name__ == "__main__":
    main_eda()
