[tox]
runner = uv-venv-runner
env_list = tests, lint

[testenv:py313]
deps =
    tox-uv
commands =
    uv run python --version

[testenv:tests]
deps =
    pytest
    pytest-cov
commands =
    uv run python -m pytest -v --cov=src --cov-report=xml

[testenv:format]
description = Run ruff formatting
commands =
    uv run ruff format .
    uv run ruff check --fix .

[testenv:lint]
description = Run ruff linting
commands =
    uv run ruff check .