[tox]
env_list = py314, lint, format

[testenv:py314]
deps =
    tox-uv
commands =
    python --version

[testenv:format]
description = Run ruff formatting
deps = ruff
commands =
    ruff format .

[testenv:lint]
description = Run ruff linting
deps = ruff
commands =
    ruff check .